import { AvatarFullConfig } from "react-nice-avatar";

export const avatarArr: AvatarFullConfig[] = [
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "beanie",
    hatColor: "red",
    hairColor: "red",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "oval",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "red",
    noseStyle: "short",
  },
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "blue",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "black",
    noseStyle: "short",
    hairStyle: "womanLong",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "purple",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "square",
    shirtStyle: "polo",
    shirtColor: "green",
    noseStyle: "short",
    hairStyle: "thick",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "purple",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "round",
    shirtStyle: "polo",
    shirtColor: "green",
    noseStyle: "short",
    hairStyle: "normal",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#f9c9b6",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "yellow",
    noseStyle: "short",
    hairStyle: "mohawk",
  },
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "turban",
    hatColor: "#FFFF",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "white",
    noseStyle: "short",
    hairStyle: "womanShort",
  },
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "none",
    hatColor: "#FFF",
    hairColor: "brown",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "square",
    shirtStyle: "short",
    shirtColor: "red",
    noseStyle: "short",
    hairStyle: "womanShort",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "beanie",
    hatColor: "orange",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#f9c9b6",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "purple",
    noseStyle: "short",
    hairStyle: "womanShort",
  },
  {
    eyeBrowStyle: "upWoman",
    sex: "man",
    hatStyle: "turban",
    hatColor: "black",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#f9c9b6",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "purple",
    noseStyle: "short",
    hairStyle: "womanShort",
  },
  {
    eyeBrowStyle: "upWoman",
    sex: "man",
    hatStyle: "beanie",
    hatColor: "red",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "round",
    shirtStyle: "short",
    shirtColor: "purple",
    noseStyle: "short",
    hairStyle: "thick",
  },
];
