import basquete from "../../assets/category/basquete.jpg";
import ciclismo from "../../assets/category/ciclismo.jpg";
import futebol from "../../assets/category/futebol.jpg";
import volei from "../../assets/category/volei.jpg";
import mergulho from "../../assets/category/mergulho.jpg";
import trilha from "../../assets/category/trilha.jpg";
import rapel from "../../assets/category/rapel.jpg";
import skate from "../../assets/category/skate.jpg";
import surf from "../../assets/category/surf.jpg";
import yoga from "../../assets/category/yoga.jpg";
import all from "../../assets/category/all.jpg";

import { AvatarFullConfig } from "react-nice-avatar";

export const categoryArr = [
  { image: all, text: "Todos" },
  { image: ciclismo, text: "Ciclismo" },
  { image: volei, text: "Vôlei" },
  { image: basquete, text: "Basquete" },
  { image: futebol, text: "Futebol" },
  { image: yoga, text: "Yoga" },
  { image: mergulho, text: "Mergulho" },
  { image: trilha, text: "Trilha" },
  { image: rapel, text: "Rapel" },
  { image: skate, text: "Skate" },
  { image: surf, text: "Surf" },
];

export const avatarArr: AvatarFullConfig[] = [
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "beanie",
    hatColor: "red",
    hairColor: "red",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "oval",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "red",
    noseStyle: "short",
    id: "0",
  },
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "blue",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "black",
    noseStyle: "short",
    hairStyle: "womanLong",
    id: "1",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "purple",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "square",
    shirtStyle: "polo",
    shirtColor: "green",
    noseStyle: "short",
    hairStyle: "thick",
    id: "2",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "purple",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "round",
    shirtStyle: "polo",
    shirtColor: "green",
    noseStyle: "short",
    hairStyle: "normal",
    id: "3",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "none",
    hatColor: "none",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#f9c9b6",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "yellow",
    noseStyle: "short",
    hairStyle: "mohawk",
    id: "4",
  },
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "turban",
    hatColor: "#FFFF",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "white",
    noseStyle: "short",
    hairStyle: "womanShort",
    id: "5",
  },
  {
    eyeBrowStyle: "up",
    sex: "woman",
    hatStyle: "turban",
    hatColor: "#FFF",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "white",
    noseStyle: "short",
    hairStyle: "womanShort",
    id: "6",
  },
  {
    eyeBrowStyle: "up",
    sex: "man",
    hatStyle: "beanie",
    hatColor: "orange",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#f9c9b6",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "purple",
    noseStyle: "short",
    hairStyle: "womanShort",
    id: "7",
  },
  {
    eyeBrowStyle: "upWoman",
    sex: "man",
    hatStyle: "turban",
    hatColor: "black",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "big",
    eyeStyle: "smile",
    faceColor: "#f9c9b6",
    mouthStyle: "smile",
    glassesStyle: "none",
    shirtStyle: "short",
    shirtColor: "purple",
    noseStyle: "short",
    hairStyle: "womanShort",
    id: "8",
  },
  {
    eyeBrowStyle: "upWoman",
    sex: "man",
    hatStyle: "beanie",
    hatColor: "red",
    hairColor: "#000",
    bgColor: "#BFFDEB",
    earSize: "small",
    eyeStyle: "smile",
    faceColor: "#AC6651",
    mouthStyle: "smile",
    glassesStyle: "round",
    shirtStyle: "short",
    shirtColor: "purple",
    noseStyle: "short",
    hairStyle: "thick",
    id: "9",
  },
];
